name: Deploy Iris Plots to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Necesario para usar set-url con GITHUB_TOKEN

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install elasticsearch pandas matplotlib seaborn scikit-learn

    - name: Run script to index and plot
      env:
        ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
        ES_API_KEY: ${{ secrets.ES_API_KEY }}
      run: python create_index.py

    - name: Set up Git credentials
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit and push changes to docs
      run: |
        git add docs/*
        git commit -m "Update plots in docs folder" || echo "No changes to commit"
        git push
